### ISSUE TITLE
Does it supports C++ coroutines?

### ISSUE THREAD

**Issue by broly** [MolecularMatters/lpp_public#3] opened 2023-02-07 07:30 UTC
I using LiveCoding in UE and when I recompile specific module, it throws access violation exception when I enter coroutine body. It seems it uses old coroutine body. Maybe some problems with addresses of jump instructions...

**Comment by MolecularMatters** [comment] 2023-02-07 07:52
Thanks for bringing this to our attention.
As you pointed out, C++20 coroutines are not supported yet, but we will look into adding support in a future update and update this issue accordingly.

**Comment by MolecularMatters** [comment] 2023-02-08 13:00
The access violation was caused by Live++ not patching relocations to COFF label symbols correctly, making the body of the new coroutine jump back into the middle of the body of the original coroutine.

This is fixed in the upcoming 2.0.5 release, making C++20 coroutines work.

Thank you again for reporting this issue!

**Closed as completed** 2023-02-08 13:00 UTC
